Printing a failure into stdout

diff --git a/run/test_and_deploy b/run/test_and_deploy
--- a/run/test_and_deploy
+++ b/run/test_and_deploy
@@ -20,6 +20,17 @@ touch "$BUILD_LOG"
 echo -e ""
 echo -e "${GREEN}Track this build in: https://${DOMAIN}/build-logs/${NUMBER_STRING}.log${NC}"
 
+function onError()
+{
+  echo -e
+  echo -e "${RED}Failed{NC}"
+  echo -e "Last 20 lines from the log: "
+  echo -e ""
+  tail -20 "$BUILD_LOG"
+  echo -e ""
+}
+trap onError ERR
+
 echo -e "${GREEN}Running tests${NC}"
 {
   echo "Running tests"
@@ -58,3 +69,5 @@ mv "${BUILD_LOG}.2" "$BUILD_LOG"
 
 echo -e "${GREEN}Success${NC}"
 echo -e ""
+
+cd nonexist
